# -*- coding: utf-8 -*-
"""ИАД лаба 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrFdZ_lsZQAN4M0OYBVvy5WbgLFGGbXH

**Карпычева Ангелина 18-АС**
"""

!pip install deepface
from deepface import DeepFace
import cv2
import pandas as pd
import matplotlib.pyplot as plt

"""Обнаружение лиц"""

def detect_face(img):
    detected_face = DeepFace.detectFace(img, detector_backend = 'ssd')
    plt.imshow(cv2.cvtColor(detected_face, cv2.COLOR_BGR2RGB))

"""Вывод оригинальной картинки"""

def detect_face_orig(img):
    orig = cv2.imread(img)
    plt.imshow(cv2.cvtColor(orig, cv2.COLOR_BGR2RGB))

"""Сравнение"""

def verify_images(img1, img2, results):
    obj = DeepFace.verify(img1, img2, distance_metric='euclidean', model_name='DeepFace', detector_backend = 'ssd')
    results.append(obj)

"""Вывод результата"""

def get_verification_results(results):
    count = 1
    for el in results:
        print(str(count)+") " + str(el["verified"]))
        count += 1

"""Загрузка картинок"""

imgs = ["/content/drive/MyDrive/ИАД_ЛАБЫ/фото_лаб3/photo_1.jpg", 
        "/content/drive/MyDrive/ИАД_ЛАБЫ/фото_лаб3/photo_2.jpg",
        "/content/drive/MyDrive/ИАД_ЛАБЫ/фото_лаб3/photo_3.jpg",
        "/content/drive/MyDrive/ИАД_ЛАБЫ/фото_лаб3/photo_4.jpg",
        "/content/drive/MyDrive/ИАД_ЛАБЫ/фото_лаб3/photo_5.jpg"]
results = []

detect_face_orig(imgs[0])

detect_face_orig(imgs[1])

detect_face_orig(imgs[2])

detect_face_orig(imgs[3])

detect_face_orig(imgs[4])

detect_face(imgs[0])

detect_face(imgs[1])

detect_face(imgs[2])

detect_face(imgs[3])

detect_face(imgs[4])

verify_images(imgs[0], imgs[2], results)
get_verification_results(results)

verify_images(imgs[0], imgs[1], results)
get_verification_results(results)

verify_images(imgs[0], imgs[3], results)
get_verification_results(results)

verify_images(imgs[2], imgs[4], results)
get_verification_results(results)